3scale-sre/marin3r

Makefile, README.md, deploy/crds/marin3r.3scale.net_envoyconfigs_crd.yaml, docs/api-reference/config.yaml, docs/api-reference/reference.asciidoc, docs/api-reference/templates/asciidoctor/gv_details.tpl, docs/api-reference/templates/asciidoctor/gv_list.tpl, docs/api-reference/templates/asciidoctor/type.tpl, docs/api-reference/templates/asciidoctor/type_members.tpl, pkg/apis/marin3r/v1alpha1/envoyconfig_types.go, pkg/apis/marin3r/v1alpha1/register.go, pkg/apis/operator/v1alpha1/register.go, pkg/controller/envoyconfig/envoyconfig_controller_test.go, pkg/controller/envoyconfigrevision/envoyconfigrevision_controller.go, pkg/controller/secret/secret_controller.go
* Link to generated api reference form README
* Resources for automatic generation of api reference docs
* Fix some names that had slipped away from the api rename
=> Add API reference documentation

Makefile, bundle/manifests/marin3r.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/webhook/kustomization.yaml, pkg/version/version.go
Just a bump in version to test the release process.
=> Bump to v0.7.0-alpha6

docs/design/operator.md
Update the docs to match recent changes in the implementation.
=> Update documentation on how certificate renewal works

README.md
Fixes the coverage badge in the main README
=> Point coverage badge to the correct branch

examples/quickstart/olm-install.yaml
=> Point the quickstart Subscription to the stable channel

controllers/operator.marin3r/discoveryservice_controller.go
The EnvoyBootstrap resource has been deprecated in favour of an init container that generates the envoy static bootstrap configuration for each envoy Pod (see #100).
This PR adds code so the controller deletes EnvoyBootstrap resources for already existing discoveryservices to save users from having to perform manual cleanup of those during the upgrade process.
/kind feature
/assign
=> Add code to automatically cleanup EnvoyBootstraps 

Makefile, bundle.Dockerfile, bundle/manifests/marin3r.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/kustomization.yaml, config/webhook/kustomization.yaml, docs/api-reference/reference.asciidoc, pkg/version/version.go, test/e2e/marin3r/envoydeploymet_suite_test.go, test/e2e/marin3r/sidecar_suite_test.go
Bumps release v0.8.0, which will get added to the stable OLM channel.
/kind automation
/assign
=> Release v0.8.0

Makefile, apis/marin3r/v1alpha1/envoyconfig_types.go, apis/marin3r/v1alpha1/envoyconfigrevision_types.go, apis/operator.marin3r/v1alpha1/discoveryservice_types.go, apis/operator.marin3r/v1alpha1/discoveryservicecertificate_types.go, apis/operator.marin3r/v1alpha1/envoydeployment_types.go, bundle/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml, bundle/manifests/marin3r.3scale.net_envoyconfigs.yaml, bundle/manifests/marin3r.clusterserviceversion.yaml, bundle/manifests/operator.marin3r.3scale.net_discoveryservicecertificates.yaml, bundle/manifests/operator.marin3r.3scale.net_discoveryservices.yaml, bundle/manifests/operator.marin3r.3scale.net_envoydeployments.yaml, config/crd/bases/marin3r.3scale.net_envoyconfigrevisions.yaml, config/crd/bases/marin3r.3scale.net_envoyconfigs.yaml, config/crd/bases/operator.marin3r.3scale.net_discoveryservicecertificates.yaml, config/crd/bases/operator.marin3r.3scale.net_discoveryservices.yaml, config/crd/bases/operator.marin3r.3scale.net_envoydeployments.yaml, config/manager/kustomization.yaml, config/manifests/bases/marin3r.clusterserviceversion.yaml, config/webhook/kustomization.yaml, pkg/version/zz_generated.go
Just a small update in the csv description and the custom resources descriptions.
/assign
=> Update CSV and custom resource descriptions

Makefile
Use the envtest-setup tool now that I have discovered that it wasn't working due to the k8s version (envtest from controller-runtime 0.8.3 does not support k8s v1.20+).
/kind feature
/assign
=> Use new envtest-setup tool

bundle/manifests/marin3r.clusterserviceversion.yaml, config/manifests/bases/marin3r.clusterserviceversion.yaml
=> Add operator category to the csv

pkg/discoveryservice/xdss/stats/collector.go, pkg/discoveryservice/xdss/stats/collector_test.go, pkg/discoveryservice/xdss/stats/kv.go, pkg/discoveryservice/xdss/stats/stats.go, pkg/discoveryservice/xdss/stats/stats_test.go, pkg/reconcilers/marin3r/envoyconfigrevision/status_test.go, pkg/reconcilers/operator/discoveryservicecertificate/reconcile_certificate.go, pkg/reconcilers/operator/discoveryservicecertificate/reconcile_certificate_test.go, pkg/util/clock/clock.go
Fixes the info metric which was showing stale values. The calculation of this metric is slightly more complex than I originally thought. Now it should work, I have also added tests that validate the metrics generation works as expected.
/kind bug
/assign
=> Fix info metrics

Makefile, bundle/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml, bundle/manifests/marin3r.3scale.net_envoyconfigs.yaml, bundle/manifests/marin3r.clusterserviceversion.yaml, bundle/manifests/operator.marin3r.3scale.net_discoveryservicecertificates.yaml, bundle/manifests/operator.marin3r.3scale.net_discoveryservices.yaml, config/manager/kustomization.yaml, config/webhook/kustomization.yaml, docs/api-reference/reference.asciidoc, pkg/image/zz_generated.go, pkg/version/zz_generated.go
Includes: #159 #161
Tested in dev environment with v0.11.1-alpha.0
=> Release v0.11.1

apis/marin3r/v1alpha1/resources.go, pkg/envoy/resources/generator.go, pkg/envoy/resources/v3/resources.go, pkg/envoy/resources/v3/resources_test.go, pkg/reconcilers/marin3r/envoyconfigrevision/cache.go, pkg/reconcilers/marin3r/envoyconfigrevision/cache_test.go
Implements the feature request at #169
/kind feature
/assign
=> Implement the 'validationContext' secret blueprint

controllers/operator.marin3r/envoydeployment_controller.go
Fixes a very minor bug in the EnvoyDeployment controller, which was missing some watches over the child resources.
/kind bug
/assign
/ok-to-test
=> Subscribe the controller to the appropriate events

.github/workflows/catalog.yaml
/kind bug
/kind release
/assign
=> Remove conditional login

catalog/marin3r/stable-channel.yaml
=> Trigger catalog build

docs/release.md
Documentation to add changes to the release process.
/assign
=> Update release docs after catalog format change

Makefile, bundle/manifests/marin3r.clusterserviceversion.yaml, catalog/marin3r/alpha-channel.yaml, config/manager/kustomization.yaml, config/webhook/kustomization.yaml, pkg/image/zz_generated.go, pkg/version/zz_generated.go
=> Bump to v0.13.1

Makefile, docs/api-reference/config.yaml, docs/api-reference/reference.asciidoc
* Fixes refdocs generation.
* Updates refdocs
/kind fix
/assign
=> Fix refdocs generation

api/go.mod, go.mod
toolchain go1.24.0 - added to go.mod and api/go.mod
=> add go toolchain to go.mod

.github/workflows/release.yaml
=> Fix envvar name

docs/release.md
=> Update the release docs
