3scale-sre/marin3r

pkg/controller/envoyconfig/envoyconfig_controller.go

This avoids a possible  race condition if the envoyconfig object is created an deleted in a very fast manner

Fix the order in which the finalizer is added and removed

---

pkg/controller/discoveryservice/enabled_namespaces.go

The admin port needs to be enabled in envoy pods so metrics can be scrapped

Enable admin port on envoy sidecars

---

pkg/common/kubernetes_types.go
pkg/controller/discoveryservice/ca_certificate.go
pkg/controller/discoveryservice/cluster_role.go
pkg/controller/discoveryservice/cluster_role_binding.go
pkg/controller/discoveryservice/common.go
pkg/controller/discoveryservice/deployment.go
pkg/controller/discoveryservice/discoveryservice_controller.go
pkg/controller/discoveryservice/enabled_namespaces.go
pkg/controller/discoveryservice/mutating_webhook_config.go
pkg/controller/discoveryservice/server_certificate.go
pkg/controller/discoveryservice/service.go
pkg/controller/discoveryservice/service_account.go
pkg/controller/discoveryservice/signer.go
pkg/reconcilers/deployment.go
pkg/reconcilers/deployment_test.go

Create a generic Deployment reconciler that can be used from several controllers. Also fix a bug detected in the reconciliation of the MutatingWebhookConfiguration.

Generic deployment reconciler

---

pkg/util/pki/generate.go

For some reason the webhook fails (api server cpmplains about tls handshake error) in openshift 4.3 if certificates are signed using ECDSA 256. Changing to RSA 2048 fixes the problem.

Fix an openshift bug in the webhook by changing certificate signing to rsa

---

config/crd/bases/envoy.marin3r.3scale.net_envoyconfigrevisions.yaml
config/crd/bases/envoy.marin3r.3scale.net_envoyconfigs.yaml
config/crd/bases/operator.marin3r.3scale.net_discoveryservicecertificates.yaml
config/crd/bases/operator.marin3r.3scale.net_discoveryservices.yaml

controller-gen v0.3.0, intended to be used with
operator-sdk v1.1.0 introduces formatting changes.
This commit regenerates the manifests to include
the regeneration of manifests with this controller-gen
version to be consistent with it.

Regenerate manifests using controller-gen v0.3.0

---

docs/development/README.md

This PR fixes broken link references to the `starting a kind kubernetes cluster` section.

doc/development: fix starting a cluster broken links

---

Makefile

If a user didn't previously have bin/kuttl installed the e2e target failed due to needing that command.
This PR adds kuttl as a prerequisite of the e2e target.

Makefile: Add kuttl as a prerequisite of e2e target

---

apis/operator/v1alpha1/discoveryservice_types.go
apis/operator/v1alpha1/discoveryservice_types_test.go
apis/operator/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/operator.marin3r.3scale.net_discoveryservices.yaml
controllers/operator/deployment.go
docs/api-reference/reference.asciidoc
pkg/reconcilers/deployment_test.go

Hi,
This PR adds configurable resource requests and limits for the `DiscoveryService` deployment through the `DiscoveryService` custom resource.
Some decisions:
* By default, if no resources are provided no resource requests and limits are set (as before this PR)
Some behavior details:
* In Kubernetes two different quantities can be semantically equal. For example, for CPU `1000m` and `1` are equivalent. In this case in the deployment it's always converted to `1`. The implementation performs semantic comparison so if 1 is set in the `DiscoveryService` cpu resource request, and then 1000m is set, NO difference is detected at the Deployment level (and thus, a redeploy of the Deployment is not triggered).
Pending:

Add configurable resource requirements for DiscoveryService

---

Makefile

This PR adds the ability to get the `crd-ref-docs` binary to generate the CRD documentation as a Makefile target.
This new target has also been added as a prerequisite of the `refdoc` target.
With this, a user does not need to manually download the `crd-ref-docs` binary to be able to generate the documentation

Makefile: Add target to get crd-ref-docs locally to the project

---

config/manager/manager.yaml

We have seen that under some conditions, controller-manager needs on startup more than 100 MB (which was the limit), so OMMKiller was acting, leaving the pod on `CrashLoopBackoff` status (average memory usage seems 100Mb).
So, I have increased  memory requests to 100MB (was the average usage), and a limit of 300Mb (which should be enough for most of the scenarios).

Increase memory request/limit of controller-manager

---

README.md
pkg/webhooks/podv1mutator/sidecar.go
pkg/webhooks/podv1mutator/sidecar_test.go

This PR adds configurable resource requirements for Envoy sidecar in Webhook.
Design:
The following annotations have been created that can be added into a ServiceDiscovery object.
```
marin3r.3scale.net/resources.limits.cpu
marin3r.3scale.net/resources.limits.memory
marin3r.3scale.net/resources.requests.cpu
marin3r.3scale.net/resources.requests.memory
```
The values have to follow the format of a Kubernetes `Quantity` https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#quantity-resource-core.
Because a `Quantity` cannot be specified as the empty string if a user specifies one of those annotation keys and it sets its value as the empty string `""` an error is returned at code level. This is one of the reasons the code implementation of the quantities parsing is …

Add configurable resource requirements for Envoy sidecar in Webhook

---

controllers/marin3r/envoyconfigrevision_controller.go
controllers/marin3r/envoyconfigrevision_controller_suite_test.go
controllers/marin3r/envoyconfigrevision_controller_test.go
pkg/reconcilers/marin3r/envoyconfigrevision/cache.go

This should have been already fixed but looks like both spec resources and secrets were returning the same error type. This commit fixes that and also adds test to avoid future regressions.

Fix: do not taint revisions with Secret related errors

---

Makefile
bundle.Dockerfile
bundle/manifests/marin3r.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml
controllers/operator.marin3r/discoveryservice_controller.go
controllers/operator.marin3r/envoydeployment_controller.go
pkg/version/version.go

ManageError(...) and ManageSuccess(...) from https://github.com/redhat-cop/operator-utils have functionality to manage the status of the custom resource after each reconcile, either for success or for error situations. We are not currently using this functionality as the status of marin3r custom resources does not support this.
Furthermore, ManageError is causing some spurious panics in reconcile loops when the custom resource cannot be retrieved for some reason. A first look into ManageError seems to point to the problem being that ManageError only restrains itslef from trying to access the fields in the custom resource if the api call returned a "not found" error. The panic occurs when a different api/client error is returned and then the function tries to access the struct, which just …

Drop usage of ManageError and ManageSuccess functions

---

controllers/marin3r/envoyconfigrevision_controller.go
controllers/marin3r/secrets_controller.go
controllers/marin3r/suite_test.go
examples/local/envoy-client-bootstrap.yaml
go.mod
go.sum
pkg/discoveryservice/manager.go
pkg/discoveryservice/xds_server.go
pkg/discoveryservice/xds_server_test.go
pkg/discoveryservice/xdss/stats/kv.go
pkg/discoveryservice/xdss/stats/kv_test.go
pkg/discoveryservice/xdss/stats/query.go
pkg/discoveryservice/xdss/stats/query_test.go
pkg/discoveryservice/xdss/stats/report.go
pkg/discoveryservice/xdss/stats/report_test.go
pkg/discoveryservice/xdss/stats/stats.go
pkg/discoveryservice/xdss/v2/cache.go
pkg/discoveryservice/xdss/v2/callbacks.go
pkg/discoveryservice/xdss/v2/callbacks_test.go
pkg/discoveryservice/xdss/v3/callbacks.go
pkg/discoveryservice/xdss/v3/callbacks_test.go
pkg/envoy/resources/type_urls.go
pkg/reconcilers/marin3r/envoyconfig/reconcile_revisions.go
pkg/reconcilers/marin3r/envoyconfig/reconcile_revisions_test.go
pkg/reconcilers/marin3r/envoyconfigrevision/cache.go
pkg/reconcilers/marin3r/envoyconfigrevision/finalize.go
pkg/reconcilers/marin3r/envoyconfigrevision/status.go
pkg/reconcilers/marin3r/envoyconfigrevision/status_test.go
pkg/util/backoff/backoff.go
pkg/util/k8s/util.go

This PR includes the following:
* Fixed a bug affecting reconcile of EnvoyConfigRevision status: d7687ea600d0293bb62e1146cd195e3e5d631f87
* Implemented a mechanism to internally store statistics related to the xDS protocol messages interchanged between clients and the discovery service: 24e5b59e4636612f11adacf9b7ed5a471d2cc9af
* Reimplemented the self-healing using the internal xDS stats: 1b17645cd666ac48be2d399189b56fe483b9e8d4
* Implemented a backoff algorithm to avoid overloading the envoy clients with retries from the discovery service: 86d1b6dc8ff8aa8f3d19040cebf757f177a37269
/kind feature
/assign

Reimplement self-healing using internal statistics

---

pkg/envoy/bootstrap/v3/bootstrap.go
pkg/envoy/bootstrap/v3/bootstrap_test.go
pkg/envoy/resources/v3/resources.go

This is a trivial change but will hopefully save somebody some time when they decide to upgrade to Envoy v0.17.x.
I made a previous try at this in PR #88 but that was bad. This is a second try.
This applies only to the V3 protocol.
This impacts the tls_certificate_sds_secret.json config file, not the response sent over the wire to xDS clients.
Marin3r generates this file and adds it to a k8s secret which is
mounted into Envoy pods. Envoy uses this file to retrieve the
bootstrap certs that allow it to talk to Marin3r over TLS. If there's
no "name" field then Envoy v0.17.0 can't process the cert, although
older Envoy versions can.
[2021-02-18 23:20:51.419][1][critical][main] [source/server/server.cc:109] error initializing configuration '/etc/envoy/bootstrap/config.json': Proto constraint …

Add a name to the V3 file-based SDS tls secret response (second try)

---

Makefile
README.md
docs/release.md

- Added documentation about release process of stable/alpha releases
- To avoid accidental stable releases creation when you want to do an alpha release, the prepare stable  target has been renamed
- Docs taken from [prometheus-exporter-operator release doc](https://github.com/3scale-ops/prometheus-exporter-operator/blob/main/docs/prometheus-exporter-crd-reference.md), so right now all our 3 operators ([prometheus-exporter-operator](https://github.com/3scale-ops/prometheus-exporter-operator), [marin3r](https://github.com/3scale-ops/marin3r) and [saas-operator](https://github.com/3scale-ops/saas-operator) ) use the exactly same release process (easier maintenance using all of them the same).
/assign

Add documentation about the operator release process

---

go.mod
go.sum

The fixes we had in our fork have already been merged upstream:
* https://github.com/redhat-cop/operator-utils/pull/68
* https://github.com/redhat-cop/operator-utils/pull/69
/kind cleanup
/assign

Back to upstream for operator-utils module

---

cmd/initmanager.go

Just a quality of life improvement so you can check the generated config directly in the container logs. There is no other way to check the generated config as we are now using an empty base image that does not have a shell to actually inspect the file inside the container.
/kind feature
/assign

Print the config generated by the init-manager for easy troubleshooting

---

Makefile
apis/operator.marin3r/v1alpha1/envoydeployment_types.go
apis/operator.marin3r/v1alpha1/envoydeployment_types_test.go
apis/operator.marin3r/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml
bundle/manifests/marin3r.clusterserviceversion.yaml
bundle/manifests/operator.marin3r.3scale.net_envoydeployments.yaml
config/crd/bases/operator.marin3r.3scale.net_envoydeployments.yaml
config/manager/kustomization.yaml
config/manifests/bases/marin3r.clusterserviceversion.yaml
config/webhook/kustomization.yaml
controllers/operator.marin3r/envoydeployment_controller.go
pkg/reconcilers/operator/envoydeployment/generators/deployment.go
pkg/reconcilers/operator/envoydeployment/generators/generator.go
pkg/version/version.go

'podAffinity' was a poor choice for naming the field because it's basically the `affinity` field of a Pod spec. It's best if the naming is the same. This field has not make it yet to a stable release, so there is no problem in changing it.
/kind feature
/assign

Rename field 'podAffinity' to just 'affinity' in EnvoyDeployment resource

---

.dockerignore

We were sending a bunch of files to the Docker daemon that aren't
relevant to creating images. Adding a few exclusions cuts the build
context from ~320MB to ~6MB. This makes building a little more snappy
on slow machines.

Reduce the size of the docker build context

---

pkg/reconcilers/marin3r/envoyconfig/revisions/sort.go
pkg/reconcilers/marin3r/envoyconfig/revisions/sort_test.go

SortByPublication had a bug where it was checking only one of the
candidates' versions but not the other. If there are only two
candidates to be sorted then one's version wasn't being examined so
the sort ended up being based on publish date only, ignoring the
version.
Now we check both candidates' versions so version is always the
primary sort key, even when there are only two candidates.

Correctly sort ECRs when there are only two in the list

---

controllers/marin3r/envoyconfig_controller_suite_test.go
controllers/marin3r/envoyconfigrevision_controller_suite_test.go
controllers/marin3r/envoyconfigrevision_controller_test.go
controllers/marin3r/suite_test.go
pkg/discoveryservice/xds_server.go
pkg/discoveryservice/xds_server_test.go
pkg/discoveryservice/xdss/interface.go
pkg/discoveryservice/xdss/v3/cache.go
pkg/discoveryservice/xdss/v3/cache_test.go
pkg/discoveryservice/xdss/v3/callbacks_test.go
pkg/discoveryservice/xdss/v3/snapshot.go
pkg/discoveryservice/xdss/v3/snapshot_test.go
pkg/reconcilers/marin3r/envoyconfigrevision/cache.go
pkg/reconcilers/marin3r/envoyconfigrevision/cache_test.go
pkg/reconcilers/marin3r/envoyconfigrevision/status_test.go

The tests of different packages access the internal structure of the snapshot cache to validate correct behaviour. This causes a lot of work each time the internal structure of the snapshot cache changes in upstream go-control-plane repo. This PR reworks the cache to make use of new funcions in go-control-plane that make it easier to write/read to/from the cache and confines any access to the internal structure to just the pkg/discoveryservice/xdss/v3 package.
/kind feature
/assign

Rework the SnapshotCache

---

controllers/operator.marin3r/discoveryservice_controller.go
controllers/operator.marin3r/discoveryservice_controller_suite_test.go
controllers/operator.marin3r/discoveryservicecertificate_controller.go
controllers/operator.marin3r/discoveryservicecertificate_controller_suite_test.go
pkg/reconcilers/operator/discoveryservice/generators/certificate_root.go
pkg/reconcilers/operator/discoveryservice/generators/certificate_root_test.go

Adds a new event handler in the DiscoveryServiceCertificate controller to trigger a reconcile of any certificate that has its issuer certificate modified. After this, it is safe to enable auto-renewal of the discovery service CA certificate.
/kind feature
/assign
Note for reviewers: https://github.com/3scale-ops/marin3r/pull/149 needs to be merged first and then I will rebase.

Auto renew ca certificate

---

pkg/reconcilers/marin3r/envoyconfig/status.go
pkg/reconcilers/marin3r/envoyconfig/status_test.go

This PR fixes the problem found in #156.
Release 0.11.0 will ship with this temporary fix. Release 0.11.1 will ship with #155.
/kind bug
/assign

Ensure message property is always set in RollbackFailed condition

---

pkg/envoy/serializer/v3/serializer.go
pkg/envoy/serializer/v3/serializer_test.go

Make the unmarshal possible for any proto message, not just the top level ones. This is useful for when the serializer package is used form other project.
/kind feature
/assign

Don't restrict the types that can be unmarshalled

---

Makefile
apis/operator.marin3r/v1alpha1/discoveryservice_types.go
cmd/discoveryservice.go
config/crd/bases/operator.marin3r.3scale.net_discoveryservices.yaml
config/crd/bases/operator.marin3r.3scale.net_envoydeployments.yaml
controllers/operator.marin3r/discoveryservice_controller.go
examples/local/envoy-client-bootstrap.yaml
hack/gen-certs.sh
pkg/discoveryservice/xds_server.go
pkg/discoveryservice/xds_server_test.go
pkg/reconcilers/operator/discoveryservice/generators/certificate_client.go
pkg/reconcilers/operator/discoveryservice/generators/deployment.go
pkg/reconcilers/operator/discoveryservice/generators/deployment_test.go
pkg/reconcilers/operator/discoveryservice/generators/generator.go

Some improvements to the discovery service, most notable the implementation of healthz checks for this pod. I have added a gRPC healthz service to the same gRPC server where the xDS service runs. This checkis then  aggregated by controller-runtime with the typical "ping" healthz checks we use for controllers.
This PR closes #46
/kind feature
/assign
/ok-to-test

Discovery service server improvements

---

apis/marin3r/v1alpha1/resources.go
apis/operator.marin3r/v1alpha1/zz_generated.deepcopy.go

Add deprecation notice on the `spec.envoyResources.secrets[*].ref` field. The code ignores this field and should be removed in an upcoming release. Actually use of the whole `spec.envoyResources` is now deprecated, but being explicit with this anyway.
Also adding some changes to the generated file `apis/operator.marin3r/v1alpha1/zz_generated.deepcopy.go`  which I missed from a previous PR.
/assign
/ok-to-test

Add deprecation notice on field

---

Makefile
controllers/marin3r/envoyconfigrevision_controller.go
pkg/discoveryservice/xdss/stats/stats.go
pkg/discoveryservice/xdss/stats/stats_test.go
pkg/reconcilers/marin3r/envoyconfigrevision/status_test.go

This PR raises the number of NACKs required to consider an envoy Pod as failing to 5. So far, a single failure was enough to mark a pod as failing to load a given configuration revision. This was problematic when running a single pod setup, where a single failure would cause a revision to get tainted.
The change also has the side effect of making the taint process much slower, due to the fact that we now must wait for 5 failures and there's an exponential backoff mechanism in place when failures occur. To improve this a bit I have reduced the periodic reconcile of EnvoyConfigRevisions to 30 seconds.
/kind bug
/assign
/ok-to-test

Harden requirements for taint

---

Makefile
README.md
apis/marin3r/v1alpha1/resources.go
bundle/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml
bundle/manifests/marin3r.3scale.net_envoyconfigs.yaml
bundle/manifests/marin3r.clusterserviceversion.yaml
bundle/manifests/operator.marin3r.3scale.net_discoveryservices.yaml
bundle/manifests/operator.marin3r.3scale.net_envoydeployments.yaml
config/crd/bases/marin3r.3scale.net_envoyconfigrevisions.yaml
config/crd/bases/marin3r.3scale.net_envoyconfigs.yaml
config/manager/kustomization.yaml
config/manifests/bases/marin3r.clusterserviceversion.yaml
config/samples/marin3r_v1alpha1_envoyconfig.yaml
config/test/manager_patch.yaml
config/webhook/kustomization.yaml
controllers/marin3r/envoyconfigrevision_controller.go
docs/api-reference/reference.asciidoc
docs/design/discovery-service.md
docs/walkthroughs/configuration-validation.md
docs/walkthroughs/envoy-connection-draining-on-shutdown.md
docs/walkthroughs/path-routing-envoydeployment.md
docs/walkthroughs/self-healing.md
docs/walkthroughs/tls-offloading-sidecars.md
pkg/image/zz_generated.go
pkg/version/zz_generated.go

* Updates docs to v0.12.0
* Bumps version to v0.12.0
* Updates API ref docs
* Updates CRDs
* Updates CSV for v0.12.0
* Removes links for old walkthroughs and examples from main readme
/kind release
/assign
/ok-to-test

Release v0.12.0

---

cmd/discoveryservice.go
pkg/discoveryservice/xds_server.go
pkg/reconcilers/operator/discoveryservice/generators/deployment.go
pkg/reconcilers/operator/discoveryservice/generators/deployment_test.go

With the addition of health checks, the rollout of new versions of the discovery service is slower because the new pod takees some seconds to pass the health checks. This makes that both the old controllers and the new ones run in parallel for some seconds, trying to write to the same EnvoyConfigRevisions and causing problems. To fix this:
* Change the Deployment rollout strategy to "replace"
* Add controller lock
* Shutdown the xDS sever faster, without graceful shutdown
I have tested an upgrade from v0.11.1 to a version with the changes in this PR and it fixes the problems.
/kind bug
/priority critical-urgent
/assign
/ok-to-test

Fix rollout of the discovery service

---

.github/workflows/build.yaml
.github/workflows/catalog.yaml
.github/workflows/test.yaml
Makefile

* Updates versions of the actions used.
* Remove the caching actions as actions/setup-go@v4 already has built-in caching enabled by default
* Add an action to publish the operator catalog when changes are made to the stable channel
/kind feature
/assign

Update hg actions

---

README.md
hack/new-release.sh

/kind cleanup
Updates all links to point to the 3scale-sre org after the migration.
/kind cleanup
/assign

fix: Update the repo name with the new org

---

.github/workflows/catalog.yaml

Installs system package `qemu-user-static` in the GH workflow VM so the multi-platform catalog image can be built.
/kind fix
/assign

Fix catalog workflow

---

.github/workflows/release.yaml

As stated in
https://go.dev/doc/modules/managing-source#multiple-module-source,
having multiple go modules in a repo requires a specific tag for each
one of them.
This step was missing from the release workflow.
/kind fix
/priority important soon
/assign

Automate api/ module tag in the release workflow
